<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamMemberSeeder extends Seeder
{
    public function run(): void
    {
        $teamMembers = [
            // Principal
            [
                'department_id' => null,
                'role_id' => 1,
                'section_assigned' => null,
                'email' => 'principal@tetutvc.ac.ke',
                'name' => 'Dr. James Kariuki',
                'photo' => null,
                'qualification' => 'PhD in Education Management, University of Nairobi',
                'graduation_year' => 2010,
                'bio' => 'Dr. James Kariuki has over 20 years of experience in technical and vocational education. Under his leadership, Tetu TVC has grown to become a center of excellence in technical education.',
                'is_hod' => false,
                'phone' => '+254758660300',
            ],
            // Deputy Principal Academics
            [
                'department_id' => null,
                'role_id' => 2,
                'section_assigned' => 'Academics',
                'email' => 'deputy.academics@tetutvc.ac.ke',
                'name' => 'Mrs. Grace Wanjiku',
                'photo' => null,
                'qualification' => 'M.Sc. in Curriculum Development, Kenyatta University',
                'graduation_year' => 2015,
                'bio' => 'Mrs. Grace Wanjiku oversees all academic programs ensuring quality curriculum delivery and assessment standards across all departments.',
                'is_hod' => false,
                'phone' => '+254758660301',
            ],
            // Deputy Principal Administration
            [
                'department_id' => null,
                'role_id' => 2,
                'section_assigned' => 'Administration',
                'email' => 'deputy.admin@tetutvc.ac.ke',
                'name' => 'Mr. Peter Ochieng',
                'photo' => null,
                'qualification' => 'MBA in Human Resource Management, USIU Africa',
                'graduation_year' => 2012,
                'bio' => 'Mr. Peter Ochieng manages all administrative functions including student affairs, finance, procurement, and support services.',
                'is_hod' => false,
                'phone' => '+254758660302',
            ],
            [
                'department_id' => 1,
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.ict@tetutvc.ac.ke',
                'name' => 'Mr. David Mutua',
                'photo' => null,
                'qualification' => 'M.Sc. in Computer Science, JKUAT',
                'graduation_year' => 2018,
                'bio' => 'Mr. David Mutua leads our ICT department with expertise in software development, networking, and cybersecurity. He has industry experience working with major tech companies.',
                'is_hod' => true,
                'phone' => '+254758660303',
            ],
            [
                'department_id' => 2,
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.electrical@tetutvc.ac.ke',
                'name' => 'Eng. Sarah Kamau',
                'photo' => null,
                'qualification' => 'B.Eng. in Electrical Engineering, UON',
                'graduation_year' => 2016,
                'bio' => 'Eng. Sarah Kamau is a certified electrical engineer with hands-on experience in industrial electrical systems, instrumentation, and renewable energy.',
                'is_hod' => true,
                'phone' => '+254758660304',
            ],
            [
                'department_id' => 3,
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.hospitality@tetutvc.ac.ke',
                'name' => 'Ms. Faith Akinyi',
                'photo' => null,
                'qualification' => 'Diploma in Hotel Management, Kenya Utalii College',
                'graduation_year' => 2014,
                'bio' => 'Ms. Faith Akinyi brings over 10 years of hospitality industry experience, having worked in top hotels across East Africa before joining academia.',
                'is_hod' => true,
                'phone' => '+254758660305',
            ],
            [
                'department_id' => 4,
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.mechanical@tetutvc.ac.ke',
                'name' => 'Mr. Joseph Njoroge',
                'photo' => null,
                'qualification' => 'Higher Diploma in Mechanical Engineering, TVC',
                'graduation_year' => 2011,
                'bio' => 'Mr. Joseph Njoroge is a master craftsman with expertise in automotive mechanics, welding, and fabrication. He has trained many successful technicians.',
                'is_hod' => true,
                'phone' => '+254758660306',
            ],
            [
                'department_id' => 5,
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.agriculture@tetutvc.ac.ke',
                'name' => 'Dr. Mary Nyambura',
                'photo' => null,
                'qualification' => 'PhD in Agricultural Science, Egerton University',
                'graduation_year' => 2020,
                'bio' => 'Dr. Mary Nyambura specializes in sustainable agriculture and agribusiness. She leads our agriculture programs with research-backed teaching methods.',
                'is_hod' => true,
                'phone' => '+254758660307',
            ],
            [
                'department_id' => 6,
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.fashion@tetutvc.ac.ke',
                'name' => 'Mrs. Jane Wairimu',
                'photo' => null,
                'qualification' => 'Diploma in Fashion Design, KNATCOM',
                'graduation_year' => 2013,
                'bio' => 'Mrs. Jane Wairimu is an award-winning fashion designer with a passion for teaching. Her designs have been featured in local and regional fashion shows.',
                'is_hod' => true,
                'phone' => '+254758660308',
            ],
            // Non-Academic Department HODs
            [
                'department_id' => 7, // Finance
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.finance@tetutvc.ac.ke',
                'name' => 'Mr. Robert Kimani',
                'photo' => null,
                'qualification' => 'CPA, MBA in Finance',
                'graduation_year' => 2012,
                'bio' => 'Mr. Robert Kimani oversees all financial operations including budgeting, accounting, and fee collection. He ensures transparent and efficient management of institutional funds.',
                'is_hod' => true,
                'phone' => '+254758660320',
            ],
            [
                'department_id' => 8, // Student Affairs
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.student@tetutvc.ac.ke',
                'name' => 'Mrs. Anne Wairimu',
                'photo' => null,
                'qualification' => 'Masters in Student Affairs, Egerton University',
                'graduation_year' => 2016,
                'bio' => 'Mrs. Anne Wairimu leads student welfare, clubs, sports, and counseling services. She is passionate about holistic student development and creating an enabling environment for all students.',
                'is_hod' => true,
                'phone' => '+254758660321',
            ],
            [
                'department_id' => 9, // Procurement
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.procurement@tetutvc.ac.ke',
                'name' => 'Mr. Paul Odhiambo',
                'photo' => null,
                'qualification' => 'Diploma in Procurement, KISM',
                'graduation_year' => 2014,
                'bio' => 'Mr. Paul Odhiambo manages all procurement and supply chain operations ensuring timely acquisition of quality goods and services for the institution.',
                'is_hod' => true,
                'phone' => '+254758660322',
            ],
            [
                'department_id' => 10, // Library
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'librarian@tetutvc.ac.ke',
                'name' => 'Ms. Catherine Atieno',
                'photo' => null,
                'qualification' => 'M.Lib. in Library Science, University of Nairobi',
                'graduation_year' => 2018,
                'bio' => 'Ms. Catherine Atieno is our Librarian, managing library resources, digital archives, and research support services. She ensures students have access to quality learning materials.',
                'is_hod' => true,
                'phone' => '+254758660323',
            ],
            [
                'department_id' => 11, // Sports
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.sports@tetutvc.ac.ke',
                'name' => 'Mr. David Ochieng',
                'photo' => null,
                'qualification' => 'Certificate in Sports Management, Kenya Institute of Sports',
                'graduation_year' => 2013,
                'bio' => 'Mr. David Ochieng coordinates all sports activities, athletics training, and intramural competitions. He promotes fitness and teamwork among students.',
                'is_hod' => true,
                'phone' => '+254758660324',
            ],
            [
                'department_id' => 12, // Music & Arts
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.arts@tetutvc.ac.ke',
                'name' => 'Ms. Faith Kemunto',
                'photo' => null,
                'qualification' => 'Diploma in Music & Performing Arts, Kenyatta University',
                'graduation_year' => 2017,
                'bio' => 'Ms. Faith Kemunto leads our Music & Arts programs, nurturing creative talents through music, drama, dance, and visual arts. She organizes cultural events and performances.',
                'is_hod' => true,
                'phone' => '+254758660325',
            ],
            // Non-Academic Staff
            [
                'department_id' => 7, // Finance
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'finance1@tetutvc.ac.ke',
                'name' => 'Ms. Grace Nyokabi',
                'photo' => null,
                'qualification' => 'CPA Part 2',
                'graduation_year' => 2020,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660326',
            ],
            [
                'department_id' => 10, // Library
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'library1@tetutvc.ac.ke',
                'name' => 'Mr. Samuel Maina',
                'photo' => null,
                'qualification' => 'Certificate in Library Information Science',
                'graduation_year' => 2019,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660327',
            ],
            [
                'department_id' => 10, // Library
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'library2@tetutvc.ac.ke',
                'name' => 'Ms. Judith Akinyi',
                'photo' => null,
                'qualification' => 'Diploma in Information Science',
                'graduation_year' => 2021,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660328',
            ],
            // Trainers (10 total)
            [
                'department_id' => 1,
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'trainer1@tetutvc.ac.ke',
                'name' => 'Mr. Alex Kiprono',
                'photo' => null,
                'qualification' => 'B.Sc. in Information Technology',
                'graduation_year' => 2021,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660309',
            ],
            [
                'department_id' => 1,
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'trainer2@tetutvc.ac.ke',
                'name' => 'Ms. Lucy Atieno',
                'photo' => null,
                'qualification' => 'Diploma in Computer Applications',
                'graduation_year' => 2019,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660310',
            ],
            [
                'department_id' => 2,
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'trainer3@tetutvc.ac.ke',
                'name' => 'Mr. Samuel Kiplagat',
                'photo' => null,
                'qualification' => 'Certificate in Electrical Installation',
                'graduation_year' => 2017,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660311',
            ],
            [
                'department_id' => 3,
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'trainer4@tetutvc.ac.ke',
                'name' => 'Ms. Rosemary Kemunto',
                'photo' => null,
                'qualification' => 'Certificate in Food & Beverage',
                'graduation_year' => 2020,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660312',
            ],
            [
                'department_id' => 4,
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'trainer5@tetutvc.ac.ke',
                'name' => 'Mr. Vincent Ouma',
                'photo' => null,
                'qualification' => 'Certificate in Motor Vehicle Mechanics',
                'graduation_year' => 2018,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660313',
            ],
            [
                'department_id' => 5,
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'trainer6@tetutvc.ac.ke',
                'name' => 'Mr. Francis Kigen',
                'photo' => null,
                'qualification' => 'Diploma in Agriculture',
                'graduation_year' => 2016,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660314',
            ],
            [
                'department_id' => 6,
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'trainer7@tetutvc.ac.ke',
                'name' => 'Ms. Pauline Wambui',
                'photo' => null,
                'qualification' => 'Certificate in Tailoring',
                'graduation_year' => 2019,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660315',
            ],
            [
                'department_id' => 8,
                'role_id' => 5,
                'section_assigned' => 'Sports',
                'email' => 'trainer8@tetutvc.ac.ke',
                'name' => 'Mr. John Ombogo',
                'photo' => null,
                'qualification' => 'Certificate in Sports Management',
                'graduation_year' => 2015,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660316',
            ],
            [
                'department_id' => 12,
                'role_id' => 5,
                'section_assigned' => 'Music & Arts',
                'email' => 'trainer9@tetutvc.ac.ke',
                'name' => 'Ms. Grace Moraa',
                'photo' => null,
                'qualification' => 'Diploma in Music',
                'graduation_year' => 2017,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660317',
            ],
            [
                'department_id' => 10,
                'role_id' => 5,
                'section_assigned' => 'Library',
                'email' => 'trainer10@tetutvc.ac.ke',
                'name' => 'Mr. Daniel Cheruiyot',
                'photo' => null,
                'qualification' => 'Certificate in Library Science',
                'graduation_year' => 2018,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660318',
            ],
        ];

        foreach ($teamMembers as $member) {
            DB::table('team_members')->insert($member);
        }
    }
}
