<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamMemberSeeder extends Seeder
{
    public function run(): void
    {
        $teamMembers = [
            // Principal
            [
                'department_id' => null,
                'role_id' => 1,
                'section_assigned' => null,
                'email' => 'principal@tetutvc.ac.ke',
                'name' => 'Mr. David M. Kariuki',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => 'Dedicated to excellence and leadership in education, inspiring students and staff alike.',
                'is_hod' => false,
                'phone' => '+254758660300',
            ],
            // Deputy Principals
            [
                'department_id' => null,
                'role_id' => 2,
                'section_assigned' => 'Administration',
                'email' => 'deputy.admin@tetutvc.ac.ke',
                'name' => 'Joshua Mwangi',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => 'Supporting our institution\'s vision and daily operations',
                'is_hod' => false,
                'phone' => '+254758660301',
            ],
            [
                'department_id' => null,
                'role_id' => 2,
                'section_assigned' => 'Academics',
                'email' => 'deputy.academics@tetutvc.ac.ke',
                'name' => 'Lydia Ndirangu',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => 'Supporting our institution\'s vision and daily operations',
                'is_hod' => false,
                'phone' => '+254758660302',
            ],
            // HODs - Academic Departments
            [
                'department_id' => 4, // Building and Civil
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.building@tetutvc.ac.ke',
                'name' => 'Gideon Muraguri',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660303',
            ],
            [
                'department_id' => 6, // ICT
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.ict@tetutvc.ac.ke',
                'name' => 'Ascar Jebet',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660304',
            ],
            [
                'department_id' => 2, // Hospitality
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.hospitality@tetutvc.ac.ke',
                'name' => 'Lily Mugo',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660305',
            ],
            [
                'department_id' => 3, // Fashion and Textile
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.fashion@tetutvc.ac.ke',
                'name' => 'Madam Jane',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660306',
            ],
            [
                'department_id' => 7, // Agriculture
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.agriculture@tetutvc.ac.ke',
                'name' => 'Anthony S.',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660307',
            ],
            [
                'department_id' => 1, // Cosmetology
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.cosmetology@tetutvc.ac.ke',
                'name' => 'Jacob Nyaga',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660308',
            ],
            [
                'department_id' => 8, // Mechanical
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.mechanical@tetutvc.ac.ke',
                'name' => 'Mugure Ngigi',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660309',
            ],
            [
                'department_id' => 5, // Electrical
                'role_id' => 3,
                'section_assigned' => null,
                'email' => 'hod.electrical@tetutvc.ac.ke',
                'name' => 'Mr. Josiah',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => true,
                'phone' => '+254758660310',
            ],
            // Other Leadership
            [
                'department_id' => null,
                'role_id' => 4,
                'section_assigned' => null,
                'email' => 'ilo@tetutvc.ac.ke',
                'name' => 'Madam Joan',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660311',
            ],
            [
                'department_id' => null,
                'role_id' => 5,
                'section_assigned' => null,
                'email' => 'registrar@tetutvc.ac.ke',
                'name' => 'Kenneth Muriuki',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660312',
            ],
            [
                'department_id' => null,
                'role_id' => 6,
                'section_assigned' => 'IQA Officer',
                'email' => 'faith@tetutvc.ac.ke',
                'name' => 'Faith Mwihaki',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660313',
            ],
            [
                'department_id' => null,
                'role_id' => 7,
                'section_assigned' => null,
                'email' => 'dean@tetutvc.ac.ke',
                'name' => 'Charles Omweri',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660314',
            ],
            [
                'department_id' => null,
                'role_id' => 6,
                'section_assigned' => 'Guiding and Couselling',
                'email' => 'fredrick@tetutvc.ac.ke',
                'name' => 'Fredrick M.',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660315',
            ],
            [
                'department_id' => null,
                'role_id' => 6,
                'section_assigned' => 'Academic Officer',
                'email' => 'sunday@tetutvc.ac.ke',
                'name' => 'Sunday Otieno',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660316',
            ],
            [
                'department_id' => 12, // Library
                'role_id' => 8,
                'section_assigned' => null,
                'email' => 'librarian@tetutvc.ac.ke',
                'name' => 'Mr. John',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660317',
            ],
            [
                'department_id' => null,
                'role_id' => 9,
                'section_assigned' => null,
                'email' => 'driver@tetutvc.ac.ke',
                'name' => 'Mr. George',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660318',
            ],
            [
                'department_id' => null,
                'role_id' => 10,
                'section_assigned' => null,
                'email' => 'secretary@tetutvc.ac.ke',
                'name' => 'Madam Eddah',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660319',
            ],
            [
                'department_id' => null,
                'role_id' => 11,
                'section_assigned' => 'Chief Cook',
                'email' => 'masila@tetutvc.ac.ke',
                'name' => 'Mr. Masila',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660320',
            ],
            [
                'department_id' => 11, // Sports
                'role_id' => 12,
                'section_assigned' => null,
                'email' => 'sports@tetutvc.ac.ke',
                'name' => 'Dennis Njeru',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660321',
            ],
            // Trainers
            [
                'department_id' => 4, // Building and Civil
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'felix@tetutvc.ac.ke',
                'name' => 'Felix Njeru',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660322',
            ],
            [
                'department_id' => 4,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'festus@tetutvc.ac.ke',
                'name' => 'Festus Chesaro',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660323',
            ],
            [
                'department_id' => 4,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'alphonse@tetutvc.ac.ke',
                'name' => 'Alphonse Otieno',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660324',
            ],
            [
                'department_id' => 2, // Hospitality
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'lucy@tetutvc.ac.ke',
                'name' => 'Madam Lucy O.',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660325',
            ],
            [
                'department_id' => 4,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'njeri@tetutvc.ac.ke',
                'name' => 'Madam Njeri',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660326',
            ],
            [
                'department_id' => 3, // Fashion and Textile
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'faithfashion@tetutvc.ac.ke',
                'name' => 'Madam Faith',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660327',
            ],
            [
                'department_id' => 1, // Cosmetology
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'peninah@tetutvc.ac.ke',
                'name' => 'Madam Peninah',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660328',
            ],
            [
                'department_id' => 6, // ICT
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'lawrence@tetutvc.ac.ke',
                'name' => 'Lawrence Mwaniki',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660329',
            ],
            [
                'department_id' => 6,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'titus@tetutvc.ac.ke',
                'name' => 'Titus Tum',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660330',
            ],
            [
                'department_id' => 8, // Mechanical
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'evans@tetutvc.ac.ke',
                'name' => 'Evans Odima',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660331',
            ],
            [
                'department_id' => 6,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'june@tetutvc.ac.ke',
                'name' => 'June Njagi',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660332',
            ],
            [
                'department_id' => 2,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'mercy@tetutvc.ac.ke',
                'name' => 'Madam Mercy',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660333',
            ],
            [
                'department_id' => 2,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'kioko@tetutvc.ac.ke',
                'name' => 'Mr. Kioko',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660334',
            ],
            [
                'department_id' => 4,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'dennis@tetutvc.ac.ke',
                'name' => 'Mr. Dennis',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660335',
            ],
            [
                'department_id' => 3,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'kimathi@tetutvc.ac.ke',
                'name' => 'Kimathi Mwiti',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660336',
            ],
            [
                'department_id' => 4,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'aminga@tetutvc.ac.ke',
                'name' => 'Mr. Aming\'a',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660337',
            ],
            [
                'department_id' => 6,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'graceni@tetutvc.ac.ke',
                'name' => 'Madam Grace N.',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660338',
            ],
            [
                'department_id' => 6,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'bilhah@tetutvc.ac.ke',
                'name' => 'Madam Bilhah',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660339',
            ],
            [
                'department_id' => 6,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'ambrose@tetutvc.ac.ke',
                'name' => 'Mr. Ambrose',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660340',
            ],
            [
                'department_id' => 8,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'thomas@tetutvc.ac.ke',
                'name' => 'Mr. Thomas',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660341',
            ],
            [
                'department_id' => 2,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'evelynne@tetutvc.ac.ke',
                'name' => 'Evelynne Donga',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660342',
            ],
            [
                'department_id' => 1,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'fernice@tetutvc.ac.ke',
                'name' => 'Fernice Gichevu',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660343',
            ],
            [
                'department_id' => 1,
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'monica@tetutvc.ac.ke',
                'name' => 'Madam Monica',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660344',
            ],
            [
                'department_id' => 5, // Electrical
                'role_id' => 13,
                'section_assigned' => null,
                'email' => 'okacha@tetutvc.ac.ke',
                'name' => 'Mr. Okacha',
                'photo' => null,
                'qualification' => '',
                'graduation_year' => null,
                'bio' => null,
                'is_hod' => false,
                'phone' => '+254758660345',
            ],
        ];

        foreach ($teamMembers as $member) {
            DB::table('team_members')->insert($member);
        }
    }
}
